import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";
import ClientOnly from "@/components/ClientOnly";
import RegisterModal from "@/components/Modal/RegisterModal";
import LoginModal from "@/components/Modal/LoginModal";
import ToasterProvider from "@/providers/ToasterProvider";
import getCurrentUser from "@/actions/getCurrentUser";
import RentModal from "@/components/Modal/RentModal";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={nunito.className}>
        <div>
          <ClientOnly>
            <ToasterProvider />
            <Navbar currentUser={currentUser} />
            <RegisterModal />
            <RentModal />
            <LoginModal />
          </ClientOnly>
        </div>
        <section className="py-28">{children}</section>
      </body>
    </html>
  );
}
